version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15.0'         
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # TODO: Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: npm install
      
      - run:
          name: Set Environment Variables
          command: npm run set_env

      - run:
          name: Build
          command: npm run api:build
      # TODO: Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            echo "TODO: Lint the frontend"

      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "TODO: Build the frontend app"
            npm run frontend:build
      # TODO: Build the backend API      
      - run:
          name: API Build 
          command: |
            echo "TODO: Build the backend API"
            npm run api:build
      
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python3-pip python-dev
      - run:
          name: Install AWS dependencies
          command: |
            sudo pip install awsebcli
            sudo pip install awscli
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME
            eb setenv POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            eb setenv POSTGRES_HOST=$POSTGRES_HOST
            eb setenv POSTGRES_DB=$POSTGRES_DB
            eb setenv AWS_BUCKET=$AWS_BUCKET
            eb setenv AWS_REGION=$AWS_REGION
            eb setenv AWS_PROFILE=$AWS_PROFILE
            eb setenv JWT_SECRET=$JWT_SECRET
            eb setenv URL=$URL
      # - run:
      #     name: Configure AWS credentials
      #     commands: |
      #       aws co     
      - run:
          name: Deploy Api
          # TODO: Install, build, deploy in both apps
          command: npm run api:deploy
      - run:
          name: Deploy Frontend
          # TODO: Install, build, deploy in both apps
          command: npm run frontend:deploy
      

  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '14.15.0' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: npm run deploy
            
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
